<a href="https://colab.research.google.com/github/pflashgary/BIOF509/blob/master/Numba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!apt-get install nvidia-cuda-toolkit
!pip3 install numba

import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/lib/nvidia-cuda-toolkit/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/lib/x86_64-linux-gnu/libnvvm.so"


Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-430
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  cpp-6 fonts-dejavu-core fonts-dejavu-extra g++-6 gcc-6 gcc-6-base
  libaccinj64-9.1 libasan3 libatk-wrapper-java libatk-wrapper-java-jni
  libcublas9.1 libcudart9.1 libcufft9.1 libcufftw9.1 libcuinj64-9.1
  libcurand9.1 libcusolver9.1 libcusparse9.1 libgcc-6-dev libnppc9.1
  libnppial9.1 libnppicc9.1 libnppicom9.1 libnppidei9.1 libnppif9.1
  libnppig9.1 libnppim9.1 libnppist9.1 libnppisu9.1 libnppitc9.1 libnpps9.1
  libnvblas9.1 libnvgraph9.1 libnvrtc9.1 libnvtoolsext1 libnvvm3
  libstdc++-6-dev libthrust-dev libvdpau-dev libxxf86dga1 nvidia-cuda-dev
  nvidia-cuda-doc nvidia-cuda-gdb nvidia-profiler nvidia-visual-profiler
  openjdk-8-jre x11-utils
Suggested packages:
  gcc-6-locales g++-6-multilib gcc-6-d

In [0]:
"""
Created on 4 Dec 2019
@author: Pegah Faegh
"""

from numba import guvectorize
import numpy as np
from timeit import default_timer as timer

@guvectorize(['void(int64[:,:], int64[:,:], int64[:,:])'],
             '(m,n),(n,p)->(m,p)')
def AstarBwith(A, B, C):
    m, n = A.shape
    n, p = B.shape
    for i in range(m):
        for j in range(p):
            C[i, j] = 0
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]

n = 1000
A = np.random.randint(n,size=(n, n))
B = np.random.randint(n,size=(n, n))

start = timer()
C = AstarBwith(A, B)
gpu_time = timer() - start
print("with GPU took %f seconds" % gpu_time)


print("C = A*B")
print(":\n%s" % C)


def AstarBwithout(A, B):
    m, n = A.shape
    n, p = B.shape
    for i in range(m):
        for j in range(p):
            C[i, j] = 0
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    return C

start = timer()
C = AstarBwithout(A, B)
without_gpu_time = timer() - start
print("with GPU took %f seconds" % without_gpu_time)

print("C = A*B")
print(":\n%s" % C)






with GPU took 1.473915 seconds
C = A*B
:
[[248144259 249283390 259713359 ... 245908890 251509173 254417723]
 [251235322 255391853 261864514 ... 247144533 253725702 251316554]
 [257955801 255126461 260889119 ... 250253505 252348172 260120703]
 ...
 [248467597 248912991 254407567 ... 244846020 248935883 246899760]
 [244886881 246486319 252161011 ... 244232705 244174493 245337172]
 [236165644 240505234 249428877 ... 233985618 243411660 235239035]]
